### PR TITLE
added mask attribute to Detection and draw_mask method

### PR DESCRIPTION
**Pull request by SharifElfouly**
Just a simple way to visualize predicted masks.

### CODE REVIEW

**Comment by joaqo** [comment]
Hi, thanks for the PR! As I mentioned in the other issue, we weren't really thinking of adding support for mask drawing atm. Still, there may be use cases which we haven't considered, and maybe your use case falls under this category. So I gotta ask, what is your use case for this at the moment? Are you using the mask information to aid in tracking in some way, or just need to draw mask information for other purposes?

Thanks!

**Comment by SharifElfouly** [comment]
Hey, just for drawing purposes.

**Comment by joaqo** [comment]
Gotcha, we'll keep this on standby for the moment until we decide what to do with regards to segmentation. Thanks!

**Comment by facundo-lezama** [comment]
We won't be adding this feature at the moment. We may consider it in the future if we decide to add masks. Thanks!

**Pull request closed without merging**
